name: yeoda-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - gdal=3.0.2
  - geopandas
  - cartopy
  - pip
  - pip:
    - pytileproj==0.0.12
    - Equi7Grid==0.0.10
    - veranda==0.1.0
    - geospade=0.1.1
    - geopathfinder==0.1.1