name: yeoda-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - geopandas
  - cartopy
  - pip
  - pip:
    - git+https://github.com/TUW-GEO/veranda.git
    - geopathfinder
    - nbsphinx
